all: PideShop HungryVeryMuch

PideShop: src/PideShop.c includes/pide_shop.h
	gcc -o PideShop src/PideShop.c -lpthread

HungryVeryMuch: src/HungryVeryMuch.c
	gcc -o HungryVeryMuch src/HungryVeryMuch.c
